### ISSUE TITLE
Invalid Load Key <

### ISSUE THREAD

**Issue by KevinhkGong** [songweige/content-debiased-fvd#11]
Hi, when I was trying to use videomae model to compute fvd, I got this error while loading the model:
Traceback (most recent call last):
  File "/home/hgong/MagicPaint/Evaluation/Benchmarks/debiased_fvd/debiased_fvd.py", line 47, in <module>
    average_fvd = calculate_average_fvd(real_folder_path, fake_folder_path, folder_name)
  File "/home/hgong/MagicPaint/Evaluation/Benchmarks/debiased_fvd/debiased_fvd.py", line 19, in calculate_average_fvd
    evaluator = fvd.cdfvd('videomae', ckpt_path=None)
  File "/home/hgong/anaconda3/envs/fvd/lib/python3.10/site-packages/cdfvd/fvd.py", line 75, in __init__
    self.model = load_videomae_model(torch.device(device), ckpt_path).eval().to(dtype=self.model_dtype)
  File "/home/hgong/anaconda3/envs/fvd/lib/python3.10/site-packages/cdfvd/third_party/VideoMAEv2/utils.py", line 75, in load_videomae_model
    ckpt = torch.load(ckpt_path, map_location='cpu')
  File "/home/hgong/anaconda3/envs/fvd/lib/python3.10/site-packages/torch/serialization.py", line 1384, in load
    return _legacy_load(
  File "/home/hgong/anaconda3/envs/fvd/lib/python3.10/site-packages/torch/serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by songweige** [comment]
Hi Kevin, it sounds like an incomplete ckpt file. Can you check the file size of the downloaded VideoMAE-v2 ckpt file?

**Comment by KevinhkGong** [comment]
Hi songwei, I previously set ckpt_path=None as shown in the documentation so I'm not sure where the downloaded checkpoint is. After setting ckpt_path, I got this while checking the checkpoint file. It seems like it was not downloaded correctly
  <?xml version="1.0" encoding="UTF-8"?>
  <Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist.</Message>
    <RequestId>672FCEAE4C586D3435243FA3</RequestId>
    <HostId>pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com</HostId>
    <BucketName>pjlab-gvm-data</BucketName>
    <EC>0015-00000101</EC>
    <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0015-00000101</RecommendDoc>
  </Error>

**Comment by songweige** [comment]
Maybe the download link is blocked for some reason. [Here](https://github.com/songweige/content-debiased-fvd/blob/a1e037ab7cb087debd2221d14ae4a001ec054201/cdfvd/third_party/VideoMAEv2/utils.py#L55C21-L55C128) is the download link used in the code. It works fine for me. Can you check if it works on you end?

**Comment by songweige** [comment]
If it works, you can manually download it and set the ckpt_path

**Comment by KevinhkGong** [comment]
Thank you very much! This solved the issue. In addition, is it possible to set cuda visible device to run this inference?

**Comment by songweige** [comment]
Great!! Gald it helped! I think so, you could try `CUDA_VISIBLE_DEVICES=0 python...`
