### ISSUE TITLE
Can you update the pip package to include the most recent commits?

### ISSUE THREAD

**Issue by roudimit** [songweige/content-debiased-fvd#3]
I'd like to use `n_fake = 'n_full'`, but [this was added ](https://github.com/songweige/content-debiased-fvd/commit/6e09b877b65b09ac2267f4d3205c19807e8e523b) after the package [on pypi was created](https://pypi.org/project/cd-fvd/#history). Can you please update it? Thanks!

**Comment by songweige** [comment]
Thanks for catching that!! The pypi package should have been updated: https://pypi.org/project/cd-fvd/0.1.1/. Feel free to let me know if you have any other requests or questions!!

**Comment by roudimit** [comment]
Thanks!
