### ISSUE TITLE
Request for Alternative Download Link for VideoMAEv2 Checkpoint

### ISSUE THREAD

**Issue by suhyeok-jang** [songweige/content-debiased-fvd#6]
Dear writers,

I am currently working with your VideoMAEv2 model and came across an issue. The ckpt_url provided in the load_video_mae_model function within the utils.py file (located in cdfvd > third_party > VideoMAEv2) appears to be inaccessible at the moment.

Would it be possible for you to provide an alternative download link for the model checkpoint? Your assistance would be greatly appreciated.

Thank you for your time and support.

Best regards,

**Comment by songweige** [comment]
Hi @suhyeok24,

Thank you for raising this issue!! We have temporarily uploaded a copy of the checkpoint to Google Drive and you can access it through [this link](https://drive.google.com/file/d/1NYB_oWpZiUrEOrvw3vu3ZFTKKLyIAIKx/view?usp=sharing)!! When the official link is fixed, I will update the url accordingly.

**Comment by suhyeok-jang** [comment]
Thank you for prompt response. Have a good day!
